// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVNjfrkKA0ZcYrjjF1QC72EtGTp1Fkwk',
    appId: '1:575194671836:web:4b0a6e21ce2868500f6219',
    messagingSenderId: '575194671836',
    projectId: 'focusflowproject-5a59d',
    authDomain: 'focusflowproject-5a59d.firebaseapp.com',
    storageBucket: 'focusflowproject-5a59d.firebasestorage.app',
    measurementId: 'G-2H9KM3MBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZ4_Iq5bHuuGRDxFimuKgq1sfgReF1NU',
    appId: '1:575194671836:android:f1e9ba0ed5ef8f750f6219',
    messagingSenderId: '575194671836',
    projectId: 'focusflowproject-5a59d',
    storageBucket: 'focusflowproject-5a59d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Mx_6Y2Ii9cKrH095O-FDotvYVK6PSHs',
    appId: '1:575194671836:ios:6b5fd77b4737d0280f6219',
    messagingSenderId: '575194671836',
    projectId: 'focusflowproject-5a59d',
    storageBucket: 'focusflowproject-5a59d.firebasestorage.app',
    iosBundleId: 'com.example.focusFlowProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Mx_6Y2Ii9cKrH095O-FDotvYVK6PSHs',
    appId: '1:575194671836:ios:6b5fd77b4737d0280f6219',
    messagingSenderId: '575194671836',
    projectId: 'focusflowproject-5a59d',
    storageBucket: 'focusflowproject-5a59d.firebasestorage.app',
    iosBundleId: 'com.example.focusFlowProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmVNjfrkKA0ZcYrjjF1QC72EtGTp1Fkwk',
    appId: '1:575194671836:web:745fde8dd7b1aaa70f6219',
    messagingSenderId: '575194671836',
    projectId: 'focusflowproject-5a59d',
    authDomain: 'focusflowproject-5a59d.firebaseapp.com',
    storageBucket: 'focusflowproject-5a59d.firebasestorage.app',
    measurementId: 'G-C28EGLQF3M',
  );
}
